import Moment from "moment";

export const ACTION_TYPE = {
  GET_MAIN_DATA: "GET_MAIN_DATA",
  GET_MAIN_DATA_PENDING: "GET_MAIN_DATA_PENDING",
  GET_MAIN_DATA_FULFILLED: "GET_MAIN_DATA_FULFILLED",
  GET_MAIN_DATA_REJECTED: "GET_MAIN_DATA_REJECTED",
  GET_DROPDOWN_DATA: "GET_DROPDOWN_DATA",
  GET_DROPDOWN_DATA_PENDING: "GET_DROPDOWN_DATA_PENDING",
  GET_DROPDOWN_DATA_FULFILLED: "GET_DROPDOWN_DATA_FULFILLED",
  GET_DROPDOWN_DATA_REJECTED: "GET_DROPDOWN_DATA_REJECTED",
  DELETE_ITEM: "DELETE_ITEM"
};
