import Moment from "moment";

export const ACTION_TYPE = {
  GET_MAIN_DATA: "GET_MAIN_DATA",
  GET_MAIN_DATA_PENDING: "GET_MAIN_DATA_PENDING",
  GET_MAIN_DATA_FULFILLED: "GET_MAIN_DATA_FULFILLED",
  GET_MAIN_DATA_REJECTED: "GET_MAIN_DATA_REJECTED",
  GET_PRODUCT_LIST_V1: "GET_PRODUCT_LIST_V1",
  GET_PRODUCT_LIST_V1_PENDING: "GET_PRODUCT_LIST_V1_PENDING",
  GET_PRODUCT_LIST_V1_FULFILLED: "GET_PRODUCT_LIST_V1_FULFILLED",
  GET_PRODUCT_LIST_V1_REJECTED: "GET_PRODUCT_LIST_V1_REJECTED",
  GET_PRODUCT_LIST_V2: "GET_PRODUCT_LIST_V2",
  GET_PRODUCT_LIST_V2_PENDING: "GET_PRODUCT_LIST_V2_PENDING",
  GET_PRODUCT_LIST_V2_FULFILLED: "GET_PRODUCT_LIST_V2_FULFILLED",
  GET_PRODUCT_LIST_V2_REJECTED: "GET_PRODUCT_LIST_V2_REJECTED",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  CREATE_PRODUCT_PENDING: "CREATE_PRODUCT_PENDING",
  CREATE_PRODUCT_FULFILLED: "CREATE_PRODUCT_FULFILLED",
  CREATE_PRODUCT_REJECTED: "CREATE_PRODUCT_REJECTED",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_PENDING: "DELETE_PRODUCT_PENDING",
  DELETE_PRODUCT_FULFILLED: "DELETE_PRODUCT_FULFILLED",
  DELETE_PRODUCT_REJECTED: "DELETE_PRODUCT_REJECTED",
  DELETE_ITEM: "DELETE_ITEM"
};
