import Moment from "moment";

export const ACTION_TYPE = {
  GET_MAIN_DATA: "GET_MAIN_DATA",
  GET_MAIN_DATA_PENDING: "GET_MAIN_DATA_PENDING",
  GET_MAIN_DATA_FULFILLED: "GET_MAIN_DATA_FULFILLED",
  GET_MAIN_DATA_REJECTED: "GET_MAIN_DATA_REJECTED",
  GET_PRODUCT_LIST_V2: "GET_PRODUCT_LIST_V2",
  GET_PRODUCT_LIST_V2_PENDING: "GET_PRODUCT_LIST_V2_PENDING",
  GET_PRODUCT_LIST_V2_FULFILLED: "GET_PRODUCT_LIST_V2_FULFILLED",
  GET_PRODUCT_LIST_V2_REJECTED: "GET_PRODUCT_LIST_V2_REJECTED",
  DELETE_ITEM: "DELETE_ITEM"
};
